src/apps/web/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import (home, somos, gracias,
                    contacto,
                    )

app_name = 'web'

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^somos/$', somos, name='somos'),
    url(r'^gracias/$', gracias, name='gracias'),
    url(r'^contacto/$', contacto, name='contacto'),
    url(r'^somos/$', somos, name='somos'),
    # url(r'^testimonios/$', testimonios, name='testimonios'),
    # url(r'^servicios/$', servicios, name='servicios'),
    # url(r'^servicio/(?P<slug>[\w-]+)/$', servicio_detalle, name='servicio_detalle'),
    # url(r'^clientes/$', clientes, name='clientes'),
    # url(r'^cliente/(?P<slug>[\w-]+)/$', cliente_detalle, name='cliente_detalle'),
]

src/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from filebrowser.sites import site
from ckeditor_uploader import urls as ck_urls
from apps.web import urls as web_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^ckeditor/', include(ck_urls)),
    url(r'', include(web_urls, namespace='web')),
    # url(r'^localeurl/', include('localeurl.urls')),

    # url(r'', include(web_urls, namespace='web')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))


handler404 = 'apps.web.views.page_404'
handler500 = 'apps.web.views.page_500'

src/templates/web/contacto.html
{% extends "common/_base.html" %}
{% load static core_tags app_tags thumbnail %}
{% block cssadicional %}
<link rel="stylesheet" href="{% static 'js/validationform/validationEngine.jquery.css' %}" type="text/css"/>
{% endblock %}

{% block classbody %}{% endblock %}

{% block content %}
<!-- BLOQUE 6 -->
<section class="b6" style="background-image: url('{{ banner.imagen.url }}');">
	<div class="wancho b6-table">
		<div class="b6-middle">
			<div class="b6-title">
				<h1>{{ banner.titulo }}</h1>
				<div class="b6-text">
					{{ banner.texto|safe }}
				</div>
			</div>
		</div>
	</div>
</section>
<!-- BLOQUE 12 -->
<section class="b12">
	<div class="wancho">
		<div class="b12-form">
			<h2>Elije que tipo de cliente eres:</h2>
			<form method="POST">
			    {% csrf_token %}
				<div class="b12-inputradio">
					<ul>
						<li>
							<label>
								<input class="input-tipo" type="radio" name="tipo" data-input="Nombre" value="Personas" checked> <span>Personas</span>
							</label>
						</li>
						<li>
							<label>
								<input class="input-tipo" type="radio" name="tipo" data-input="Nombre de empresa" value="Empresas"> <span>Empresas</span>
							</label>
						</li>
					</ul>
				</div>
				<div class="b12-input">
					<input type="text" name="nombre" placeholder="Nombre" class="input-name validate[required]">
				</div>
				<div class="b12-input">
					<input type="text" name="email" placeholder="Email" class="validate[required]">
				</div>
				<div class="b12-input">
					<input type="text" name="telefono" placeholder="Teléfono" class="validate[required]">
				</div>
				<div class="b12-textarea">
					<textarea name="mensaje" id="" cols="30" rows="10" placeholder="Mensaje"  class="validate[required]"></textarea>
				</div>
				<div class="b12-button">
					<button class="g-btn turqueza">
						Enviar
					</button>
				</div>
			</form>
			<div class="b12-referencia">
				<div class="b12-item">
					<i class="icon-direccion"></i>
					<p>{{ info.direccion_local }}</p>
				</div>
				<div class="b12-item">
					<i class="icon-email"></i>
					<p><a href="mailto:{{ info.email }}">{{ info.email }}</a></p>
				</div>
				<div class="b12-item">
					<i class="icon-telefono"></i>
					<p><a href="tel:{{ info.telefono|tel }}">{{ info.telefono }}</a></p>
				</div>
			</div>

		</div>
	</div>
	<figure class="b12-img">
		<img src="{{ info.foto_contactanos.path|thumbnail_by_name:'366x210' }}" width="366" height="210" alt="">
	</figure>
</section>
<!-- BLOQUE 13 -->
<section class="b13">
	<div class="b13-cnt-map">
		<div class="g-btn  b13-abrir"><span>Ver mapa</span></div>
		<div class="b13-box-map">
			<div class="b13-map" id="google-maplima"></div>
			<div class="g-btn b13-cerrar"><span>Cerrar mapa</span></div>
		</div>
	</div>
</section>

{% endblock %}

{% block jsfinal %}
<script type="text/javascript" src="{% static 'js/validationform/jquery.validationEngine-es.js' %}"></script>
<script type="text/javascript" src="{% static 'js/validationform/jquery.validationEngine.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script type="text/javascript">
	$(function(){
		$("form").validationEngine('attach', {
			promptPosition : "topLeft",
			autoHidePrompt: true,
			autoHideDelay: 3000,
			binded: false,
			scroll: false
		});
		$(".b14-send").click(function(e) {
			//e.preventDefault();
			$('.b14-formulario').validationEngine('validate');
		});

		$('.input-tipo').change(function(){
			if ( $(this).is(':checked') ){
				name = $(this).attr('data-input');
				$('.input-name').attr('placeholder', name);
			}
		});
	});
	//BLOQUE 13
		   //google map
		    function initMap() {
		      var $map = $( '#google-maplima' );
		      if ( ! $map.length ) return;
		      var myLatlng = new google.maps.LatLng({{ info.coordenadas }}); // <- Your latitude and longitude
		      var styles = [
		        {
		          "featureType": "water",
		          "stylers": [
		          {
		            "color": "#eee"
		          },
		          {
		            "visibility": "on"
		          }
		          ]
		        },
		        {
		          "featureType": "landscape",
		          "stylers": [
		          {
		            "color": "#f2f2f2"
		          }
		          ]
		        },
		        {
		          "featureType": "road",
		          "stylers": [
		          {
		            "saturation": -100
		          },
		          {
		            "lightness": 45
		          }
		          ]
		        },
		        {
		          "featureType": "road.highway",
		          "stylers": [
		          {
		            "visibility": "simplified"
		          }
		          ]
		        },
		        {
		          "featureType": "road.arterial",
		          "elementType": "labels.icon",
		          "stylers": [
		          {
		            "visibility": "off"
		          }
		          ]
		        },
		        {
		          "featureType": "administrative",
		          "elementType": "labels.text.fill",
		          "stylers": [
		          {
		            "color": "#444444"
		          }
		          ]
		        },
		        {
		          "featureType": "transit",
		          "stylers": [
		          {
		            "visibility": "off"
		          }
		          ]
		        },
		        {
		          "featureType": "poi",
		          "stylers": [
		          {
		            "visibility": "off"
		          }
		          ]
		        }
		       ]
		      var mapOptions = {
		        zoom             : 15,
		        center           : myLatlng,
		        mapTypeControl   : true,
		        disableDefaultUI : true,
		        zoomControl      : true,
		        scrollwheel      : false,
		        styles           : styles,
		        draggable        : true
		      }
		      var map = new google.maps.Map(document.getElementById('google-maplima'), mapOptions);

		      var marker = new google.maps.Marker({
		          position: myLatlng,
		          icon:'{% static "img/contacto-nukleo.png" %}',
		          map: map
		      });
		    }
		    google.maps.event.addDomListener(window, 'load', initMap),


		    // script para mapa responsive

		    $(".b13-abrir").click(function(event) {
		      $(".b13-box-map").addClass('active');
		    });

		    $(".b13-cerrar").click(function(event) {
		      $(".b13-box-map").removeClass('active');
		    });
		    // fin de mapa
</script>
{% endblock %}

src/templates/web/email-contacto.html
{% load static %}
{% spaceless %}

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Formulario de Contacto| NUKLEO</title>

  <style>
  a:hover {
    text-decoration: underline !important;
  }

  td.contentblock h4 {
    color:#444444 !important;
    font-size:16px;
    line-height:24px;
    font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
    margin-top:0;
    margin-bottom:10px;
    padding-top:0;
    padding-bottom:0;
    font-weight:normal;
  }
  td.contentblock h4 a {
    color:#444444;
    text-decoration:none;
  }
  td.contentblock p {
      color:#888888;
    font-size:13px;
    line-height:19px;
    font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
    margin-top:0;
    margin-bottom:12px;
    padding-top:0;
    padding-bottom:0;
    font-weight:normal;
  }
  td.contentblock p a {
      color:#3ca7dd;
    text-decoration:none;
  }
  @media only screen and (max-device-width: 480px) {
       div[class="header"] {
            font-size: 16px !important;
       }
       table[class="table"], td[class="cell"] {
            width: 300px !important;
       }

    td[class="footershow"] {
            width: 300px !important;
       }
    table[class="hide"], img[class="hide"], td[class="hide"] {
            display: none !important;
       }
       img[class="divider"] {
          height: 1px !important;
     }
     td[class="logocell"] {
      padding-top: 15px !important;
      padding-left: 15px !important;
      width: 300px !important;
     }
       img[id="screenshot"] {
            width: 325px !important;
            height: 127px !important;
       }
    img[class="galleryimage"] {
        width: 53px !important;
            height: 53px !important;
    }
    p[class="reminder"] {
      font-size: 11px !important;
    }
    h4[class="secondary"] {
      line-height: 22px !important;
      margin-bottom: 15px !important;
      font-size: 18px !important;
    }
  }

  </style>
</head>

<body bgcolor="#e4e4e4" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" style="-webkit-font-smoothing: antialiased;width:100% !important;background:#e4e4e4;-webkit-text-size-adjust:none;">

<table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#e4e4e4">
<tr>
  <td bgcolor="#e4e4e4" width="100%">

  <table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="table">
  <tr>
    <td width="600" class="cell">

      <table width="600" cellpadding="0" cellspacing="0" border="0" class="table">
    <tr>
      <td width="250" bgcolor="#e4e4e4" class="logocell">
        <img border="0" src="{% static 'images-email/spacer.gif' %}" width="1" height="20" class="hide"><br class="hide"><img src="{{info.site}}{% static 'img/header-logo.png' %}" width="178" height="76" alt="-" style="-ms-interpolation-mode:bicubic;"><br><img border="0" src="{% static 'images-email/spacer.gif' %}" width="1" height="10" class="hide"><br class="hide"></td>
        <td align="right" width="350" class="hide" style="color:#a6a6a6;font-size:12px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;text-shadow: 0 1px 0 #ffffff;" valign="top" bgcolor="#e4e4e4"><img border="0" src="{{STATIC_URL}}images-email/spacer.gif" width="1" height="63"><br><span>NUKLEO:&nbsp;</span><strong>
        <span style="text-transform:uppercase;"> </span></strong> <span>CONTACTO&nbsp;</span>
      </td>
    </tr>
    </table>

      <table width="100%" cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td bgcolor="#85bdad" nowrap><img border="0" src="{% static 'images-email/spacer.gif' %}" width="5" height="1"></td>

        <td width="100%" bgcolor="#ffffff">

          <table width="100%" cellpadding="20" cellspacing="0" border="0">
          <tr>
            <td bgcolor="#ffffff" class="contentblock">

              <h4 class="secondary">
                <strong><p label="Title">Datos de Contacto</p></strong>
              </h4>
              <p label="Description">Han enviado el siguiente formulario:</p>

              <table cellspacing="10" style="width:100%;" id='table_contacto'>

                <tr>
                  <td style='width: 20%;'>
                    <strong>TIPO:</strong>
                  </td>
                  <td>{{ tipo }}</td>
                </tr>

                <tr>
                  <td style='width: 20%;'>
                    <strong>{% if tipo == "Personas" %}NOMBRE:{% elif tipo == "Empresas"%}NOMBRE DE LA EMPRESA:{% endif %}</strong>
                  </td>
                  <td>{{ nombre }}</td>
                </tr>

                <tr>
                  <td style='width: 20%;'>
                    <strong>EMAIL: </strong>
                  </td>
                  <td>{{ email }}</td>
                </tr>

                <tr>
                  <td style='width: 20%;'>
                    <strong>TELÉFONO: </strong>
                  </td>
                  <td>{{ telefono }}</td>
                </tr>

                <tr>
                  <td style='width: 20%;'>
                    <strong>MENSAJE: </strong>
                  </td>
                  <td>{{ mensaje }}</td>
                </tr>
              </table>

            </td>
          </tr>
          </table>

        </td>
      </tr>
      </table>
      <img border="0" src="{% static 'images-email/spacer.gif' %}" width="1" height="15" class="divider"><br>

    </td>
  </tr>
  </table>
  </td>
</tr>
</table>

</body>
</html>
{% endspaceless %}

src/templates/web/error.html
{% extends "common/_base.html" %}
{% load static %}
{% block cssadicional %}

{% endblock %}

{% block classbody %}{% endblock %}

{% block content %}
<div class="b16">
	<div class="b16-main">
		<div class="b16-inner">

			<div class="wancho">
				<div class="b16-text">
					<h3 class="b16-title">404</h3>
					<p>
						Parece que ha habido un error con la página que estás buscando.
					</p>
					<p>
						Es posible que en la entrada haya sido eliminado o que la dirección no exista
					</p>
					<a href="{% url 'web:home' %}" class="g-btn gris">
						Ir a la página principal
					</a>
				</div>

			</div>
		</div>

	</div>
	<div class="wancho">
		<div class="b16-img">
			<img src="{% static 'img/img-error.png' %}" width="155" height="214" alt="">
		</div>
	</div>
</div>
{% endblock %}

{% block jsfinal %}

<script type="text/javascript">
	$(function(){
		function fullscreen	(){
			header = $('header').outerHeight();
			footer = $('footer').outerHeight();
			alto = $(window).height();
			element = $('.b16').outerHeight();
			vWidth = $(window).width();
			if(vWidth>480){
				$('.b16').height(alto-header-footer);
			}else{
				$('.b16').removeAttr('style');
			}

		}
		fullscreen()
		$(window).resize(function(event) {
			fullscreen()
		});

	});
</script>
{% endblock %}

src/templates/web/gracias.html
{% extends "common/_base.html" %}
{% load static %}
{% block cssadicional %}

{% endblock %}

{% block classbody %}{% endblock %}

{% block content %}
<div class="b16">
	<div class="b16-main">
		<div class="b16-inner">

			<div class="wancho">
				<div class="b16-text">
					<h3 class="b16-title">Gracias</h3>
					<p>
						Por comunicarte con nosotros.
					</p>
					<p>
						Estaremos encantados de responderte a la brevedad.
					</p>
					<a href="{% url 'web:home' %}" class="g-btn gris">
						Ir a la página principal
					</a>
				</div>

			</div>
		</div>

	</div>
	<div class="wancho">
		<div class="b16-img">
			<img src="{% static 'img/img-error.png' %}" width="155" height="214" alt="">
		</div>
	</div>
</div>
{% endblock %}

{% block jsfinal %}

<script type="text/javascript">
	$(function(){
		function fullscreen	(){
			header = $('header').outerHeight();
			footer = $('footer').outerHeight();
			alto = $(window).height();
			element = $('.b16').outerHeight();
			vWidth = $(window).width();
			if(vWidth>480){
				$('.b16').height(alto-header-footer);
			}else{
				$('.b16').removeAttr('style');
			}

		}
		fullscreen()
		$(window).resize(function(event) {
			fullscreen()
		});

	});
</script>
{% endblock %}

src/templates/web/home.html
{% extends "common/_base.html" %}
{% load static thumbnail %}
{% load core_tags app_tags %}
{% block cssadicional %}
<link href="{% static 'css/jquery.bxslider.css' %}" rel="stylesheet" />

<link rel="stylesheet" href="{% static 'js/validationform/validationEngine.jquery.css' %}" type="text/css"/>
{% endblock %}

{% block classbody %}{% endblock %}

{% block content %}
   <!-- BLOQUE 1 -->



{% endblock %}

{% block jsfinal %}
<script type="text/javascript" src="{% static 'js/jquery.bxslider.min.js' %}"></script>
<script src="{% static 'js/validationform/jquery.validationEngine.js' %}"></script>
<script src="{% static 'js/validationform/jquery.validationEngine-es.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.waypoints.js' %}"></script>
<script type="text/javascript">
	$(function(){
		

	});
</script>
{% endblock %}